### ISSUE TITLE
Frequency domain beamforming instead of time domain beamforming

### ISSUE THREAD

**Issue by ghost** [tudelft-iv/occluded_vehicle_acoustic_detection#1]
Is there any reason for the frequency-domain beamforming in the beamforming.py? Isn't it easier to just use beamforming in time domain so you don't have to "split" one wav-file in multiple HDF5-Files? Does acoular handle it differently? Or is there any other reason behind it?

**Comment by tomsal** [comment]
That is a fair question. At the time it seems that this was an acoular requirement. I do not know about the current state. In addition, we wanted to split the audio files anyway to match the frame rate, so this is an additional reason to split the wav-files. Of course, there may be different ways to achieve it!

Hope this helps!

**Comment by ghost** [comment]
Thank you very much for your help! Do you guys maybe have a "direct" way of contact (like an e-mail, discord etc.) for questions regarding acoustic cameras and beamforming with acoular?

**Comment by tomsal** [comment]
The best way is probably to contact Julian via email (he's the primary contact of the paper). He can forward you depending on your questions. :)
